###############################################################################
# Created by write_sdc
###############################################################################
current_design hdecoder
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name __VIRTUAL_CLK__ -period 10.0000 
set_clock_uncertainty 0.2500 __VIRTUAL_CLK__
set_input_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {ena_i}]
set_input_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {input_ni[0]}]
set_input_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {input_ni[1]}]
set_input_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {input_ni[2]}]
set_input_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {input_ni[3]}]
set_input_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {input_ni[4]}]
set_input_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {input_ni[5]}]
set_input_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {input_ni[6]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[0]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[100]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[101]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[102]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[103]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[104]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[105]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[106]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[107]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[108]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[109]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[10]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[110]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[111]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[112]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[113]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[114]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[115]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[116]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[117]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[118]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[119]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[11]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[120]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[121]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[122]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[123]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[124]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[125]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[126]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[127]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[12]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[13]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[14]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[15]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[16]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[17]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[18]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[19]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[1]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[20]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[21]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[22]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[23]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[24]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[25]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[26]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[27]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[28]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[29]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[2]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[30]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[31]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[32]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[33]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[34]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[35]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[36]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[37]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[38]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[39]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[3]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[40]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[41]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[42]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[43]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[44]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[45]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[46]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[47]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[48]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[49]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[4]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[50]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[51]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[52]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[53]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[54]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[55]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[56]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[57]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[58]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[59]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[5]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[60]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[61]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[62]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[63]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[64]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[65]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[66]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[67]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[68]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[69]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[6]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[70]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[71]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[72]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[73]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[74]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[75]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[76]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[77]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[78]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[79]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[7]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[80]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[81]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[82]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[83]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[84]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[85]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[86]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[87]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[88]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[89]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[8]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[90]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[91]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[92]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[93]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[94]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[95]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[96]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[97]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[98]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[99]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_no[9]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[0]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[100]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[101]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[102]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[103]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[104]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[105]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[106]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[107]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[108]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[109]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[10]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[110]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[111]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[112]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[113]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[114]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[115]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[116]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[117]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[118]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[119]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[11]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[120]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[121]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[122]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[123]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[124]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[125]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[126]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[127]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[12]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[13]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[14]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[15]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[16]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[17]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[18]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[19]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[1]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[20]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[21]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[22]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[23]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[24]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[25]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[26]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[27]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[28]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[29]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[2]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[30]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[31]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[32]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[33]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[34]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[35]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[36]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[37]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[38]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[39]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[3]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[40]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[41]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[42]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[43]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[44]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[45]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[46]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[47]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[48]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[49]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[4]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[50]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[51]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[52]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[53]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[54]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[55]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[56]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[57]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[58]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[59]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[5]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[60]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[61]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[62]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[63]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[64]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[65]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[66]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[67]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[68]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[69]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[6]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[70]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[71]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[72]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[73]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[74]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[75]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[76]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[77]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[78]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[79]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[7]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[80]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[81]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[82]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[83]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[84]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[85]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[86]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[87]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[88]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[89]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[8]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[90]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[91]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[92]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[93]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[94]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[95]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[96]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[97]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[98]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[99]}]
set_output_delay 2.0000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {output_o[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0060 [get_ports {output_no[127]}]
set_load -pin_load 0.0060 [get_ports {output_no[126]}]
set_load -pin_load 0.0060 [get_ports {output_no[125]}]
set_load -pin_load 0.0060 [get_ports {output_no[124]}]
set_load -pin_load 0.0060 [get_ports {output_no[123]}]
set_load -pin_load 0.0060 [get_ports {output_no[122]}]
set_load -pin_load 0.0060 [get_ports {output_no[121]}]
set_load -pin_load 0.0060 [get_ports {output_no[120]}]
set_load -pin_load 0.0060 [get_ports {output_no[119]}]
set_load -pin_load 0.0060 [get_ports {output_no[118]}]
set_load -pin_load 0.0060 [get_ports {output_no[117]}]
set_load -pin_load 0.0060 [get_ports {output_no[116]}]
set_load -pin_load 0.0060 [get_ports {output_no[115]}]
set_load -pin_load 0.0060 [get_ports {output_no[114]}]
set_load -pin_load 0.0060 [get_ports {output_no[113]}]
set_load -pin_load 0.0060 [get_ports {output_no[112]}]
set_load -pin_load 0.0060 [get_ports {output_no[111]}]
set_load -pin_load 0.0060 [get_ports {output_no[110]}]
set_load -pin_load 0.0060 [get_ports {output_no[109]}]
set_load -pin_load 0.0060 [get_ports {output_no[108]}]
set_load -pin_load 0.0060 [get_ports {output_no[107]}]
set_load -pin_load 0.0060 [get_ports {output_no[106]}]
set_load -pin_load 0.0060 [get_ports {output_no[105]}]
set_load -pin_load 0.0060 [get_ports {output_no[104]}]
set_load -pin_load 0.0060 [get_ports {output_no[103]}]
set_load -pin_load 0.0060 [get_ports {output_no[102]}]
set_load -pin_load 0.0060 [get_ports {output_no[101]}]
set_load -pin_load 0.0060 [get_ports {output_no[100]}]
set_load -pin_load 0.0060 [get_ports {output_no[99]}]
set_load -pin_load 0.0060 [get_ports {output_no[98]}]
set_load -pin_load 0.0060 [get_ports {output_no[97]}]
set_load -pin_load 0.0060 [get_ports {output_no[96]}]
set_load -pin_load 0.0060 [get_ports {output_no[95]}]
set_load -pin_load 0.0060 [get_ports {output_no[94]}]
set_load -pin_load 0.0060 [get_ports {output_no[93]}]
set_load -pin_load 0.0060 [get_ports {output_no[92]}]
set_load -pin_load 0.0060 [get_ports {output_no[91]}]
set_load -pin_load 0.0060 [get_ports {output_no[90]}]
set_load -pin_load 0.0060 [get_ports {output_no[89]}]
set_load -pin_load 0.0060 [get_ports {output_no[88]}]
set_load -pin_load 0.0060 [get_ports {output_no[87]}]
set_load -pin_load 0.0060 [get_ports {output_no[86]}]
set_load -pin_load 0.0060 [get_ports {output_no[85]}]
set_load -pin_load 0.0060 [get_ports {output_no[84]}]
set_load -pin_load 0.0060 [get_ports {output_no[83]}]
set_load -pin_load 0.0060 [get_ports {output_no[82]}]
set_load -pin_load 0.0060 [get_ports {output_no[81]}]
set_load -pin_load 0.0060 [get_ports {output_no[80]}]
set_load -pin_load 0.0060 [get_ports {output_no[79]}]
set_load -pin_load 0.0060 [get_ports {output_no[78]}]
set_load -pin_load 0.0060 [get_ports {output_no[77]}]
set_load -pin_load 0.0060 [get_ports {output_no[76]}]
set_load -pin_load 0.0060 [get_ports {output_no[75]}]
set_load -pin_load 0.0060 [get_ports {output_no[74]}]
set_load -pin_load 0.0060 [get_ports {output_no[73]}]
set_load -pin_load 0.0060 [get_ports {output_no[72]}]
set_load -pin_load 0.0060 [get_ports {output_no[71]}]
set_load -pin_load 0.0060 [get_ports {output_no[70]}]
set_load -pin_load 0.0060 [get_ports {output_no[69]}]
set_load -pin_load 0.0060 [get_ports {output_no[68]}]
set_load -pin_load 0.0060 [get_ports {output_no[67]}]
set_load -pin_load 0.0060 [get_ports {output_no[66]}]
set_load -pin_load 0.0060 [get_ports {output_no[65]}]
set_load -pin_load 0.0060 [get_ports {output_no[64]}]
set_load -pin_load 0.0060 [get_ports {output_no[63]}]
set_load -pin_load 0.0060 [get_ports {output_no[62]}]
set_load -pin_load 0.0060 [get_ports {output_no[61]}]
set_load -pin_load 0.0060 [get_ports {output_no[60]}]
set_load -pin_load 0.0060 [get_ports {output_no[59]}]
set_load -pin_load 0.0060 [get_ports {output_no[58]}]
set_load -pin_load 0.0060 [get_ports {output_no[57]}]
set_load -pin_load 0.0060 [get_ports {output_no[56]}]
set_load -pin_load 0.0060 [get_ports {output_no[55]}]
set_load -pin_load 0.0060 [get_ports {output_no[54]}]
set_load -pin_load 0.0060 [get_ports {output_no[53]}]
set_load -pin_load 0.0060 [get_ports {output_no[52]}]
set_load -pin_load 0.0060 [get_ports {output_no[51]}]
set_load -pin_load 0.0060 [get_ports {output_no[50]}]
set_load -pin_load 0.0060 [get_ports {output_no[49]}]
set_load -pin_load 0.0060 [get_ports {output_no[48]}]
set_load -pin_load 0.0060 [get_ports {output_no[47]}]
set_load -pin_load 0.0060 [get_ports {output_no[46]}]
set_load -pin_load 0.0060 [get_ports {output_no[45]}]
set_load -pin_load 0.0060 [get_ports {output_no[44]}]
set_load -pin_load 0.0060 [get_ports {output_no[43]}]
set_load -pin_load 0.0060 [get_ports {output_no[42]}]
set_load -pin_load 0.0060 [get_ports {output_no[41]}]
set_load -pin_load 0.0060 [get_ports {output_no[40]}]
set_load -pin_load 0.0060 [get_ports {output_no[39]}]
set_load -pin_load 0.0060 [get_ports {output_no[38]}]
set_load -pin_load 0.0060 [get_ports {output_no[37]}]
set_load -pin_load 0.0060 [get_ports {output_no[36]}]
set_load -pin_load 0.0060 [get_ports {output_no[35]}]
set_load -pin_load 0.0060 [get_ports {output_no[34]}]
set_load -pin_load 0.0060 [get_ports {output_no[33]}]
set_load -pin_load 0.0060 [get_ports {output_no[32]}]
set_load -pin_load 0.0060 [get_ports {output_no[31]}]
set_load -pin_load 0.0060 [get_ports {output_no[30]}]
set_load -pin_load 0.0060 [get_ports {output_no[29]}]
set_load -pin_load 0.0060 [get_ports {output_no[28]}]
set_load -pin_load 0.0060 [get_ports {output_no[27]}]
set_load -pin_load 0.0060 [get_ports {output_no[26]}]
set_load -pin_load 0.0060 [get_ports {output_no[25]}]
set_load -pin_load 0.0060 [get_ports {output_no[24]}]
set_load -pin_load 0.0060 [get_ports {output_no[23]}]
set_load -pin_load 0.0060 [get_ports {output_no[22]}]
set_load -pin_load 0.0060 [get_ports {output_no[21]}]
set_load -pin_load 0.0060 [get_ports {output_no[20]}]
set_load -pin_load 0.0060 [get_ports {output_no[19]}]
set_load -pin_load 0.0060 [get_ports {output_no[18]}]
set_load -pin_load 0.0060 [get_ports {output_no[17]}]
set_load -pin_load 0.0060 [get_ports {output_no[16]}]
set_load -pin_load 0.0060 [get_ports {output_no[15]}]
set_load -pin_load 0.0060 [get_ports {output_no[14]}]
set_load -pin_load 0.0060 [get_ports {output_no[13]}]
set_load -pin_load 0.0060 [get_ports {output_no[12]}]
set_load -pin_load 0.0060 [get_ports {output_no[11]}]
set_load -pin_load 0.0060 [get_ports {output_no[10]}]
set_load -pin_load 0.0060 [get_ports {output_no[9]}]
set_load -pin_load 0.0060 [get_ports {output_no[8]}]
set_load -pin_load 0.0060 [get_ports {output_no[7]}]
set_load -pin_load 0.0060 [get_ports {output_no[6]}]
set_load -pin_load 0.0060 [get_ports {output_no[5]}]
set_load -pin_load 0.0060 [get_ports {output_no[4]}]
set_load -pin_load 0.0060 [get_ports {output_no[3]}]
set_load -pin_load 0.0060 [get_ports {output_no[2]}]
set_load -pin_load 0.0060 [get_ports {output_no[1]}]
set_load -pin_load 0.0060 [get_ports {output_no[0]}]
set_load -pin_load 0.0060 [get_ports {output_o[127]}]
set_load -pin_load 0.0060 [get_ports {output_o[126]}]
set_load -pin_load 0.0060 [get_ports {output_o[125]}]
set_load -pin_load 0.0060 [get_ports {output_o[124]}]
set_load -pin_load 0.0060 [get_ports {output_o[123]}]
set_load -pin_load 0.0060 [get_ports {output_o[122]}]
set_load -pin_load 0.0060 [get_ports {output_o[121]}]
set_load -pin_load 0.0060 [get_ports {output_o[120]}]
set_load -pin_load 0.0060 [get_ports {output_o[119]}]
set_load -pin_load 0.0060 [get_ports {output_o[118]}]
set_load -pin_load 0.0060 [get_ports {output_o[117]}]
set_load -pin_load 0.0060 [get_ports {output_o[116]}]
set_load -pin_load 0.0060 [get_ports {output_o[115]}]
set_load -pin_load 0.0060 [get_ports {output_o[114]}]
set_load -pin_load 0.0060 [get_ports {output_o[113]}]
set_load -pin_load 0.0060 [get_ports {output_o[112]}]
set_load -pin_load 0.0060 [get_ports {output_o[111]}]
set_load -pin_load 0.0060 [get_ports {output_o[110]}]
set_load -pin_load 0.0060 [get_ports {output_o[109]}]
set_load -pin_load 0.0060 [get_ports {output_o[108]}]
set_load -pin_load 0.0060 [get_ports {output_o[107]}]
set_load -pin_load 0.0060 [get_ports {output_o[106]}]
set_load -pin_load 0.0060 [get_ports {output_o[105]}]
set_load -pin_load 0.0060 [get_ports {output_o[104]}]
set_load -pin_load 0.0060 [get_ports {output_o[103]}]
set_load -pin_load 0.0060 [get_ports {output_o[102]}]
set_load -pin_load 0.0060 [get_ports {output_o[101]}]
set_load -pin_load 0.0060 [get_ports {output_o[100]}]
set_load -pin_load 0.0060 [get_ports {output_o[99]}]
set_load -pin_load 0.0060 [get_ports {output_o[98]}]
set_load -pin_load 0.0060 [get_ports {output_o[97]}]
set_load -pin_load 0.0060 [get_ports {output_o[96]}]
set_load -pin_load 0.0060 [get_ports {output_o[95]}]
set_load -pin_load 0.0060 [get_ports {output_o[94]}]
set_load -pin_load 0.0060 [get_ports {output_o[93]}]
set_load -pin_load 0.0060 [get_ports {output_o[92]}]
set_load -pin_load 0.0060 [get_ports {output_o[91]}]
set_load -pin_load 0.0060 [get_ports {output_o[90]}]
set_load -pin_load 0.0060 [get_ports {output_o[89]}]
set_load -pin_load 0.0060 [get_ports {output_o[88]}]
set_load -pin_load 0.0060 [get_ports {output_o[87]}]
set_load -pin_load 0.0060 [get_ports {output_o[86]}]
set_load -pin_load 0.0060 [get_ports {output_o[85]}]
set_load -pin_load 0.0060 [get_ports {output_o[84]}]
set_load -pin_load 0.0060 [get_ports {output_o[83]}]
set_load -pin_load 0.0060 [get_ports {output_o[82]}]
set_load -pin_load 0.0060 [get_ports {output_o[81]}]
set_load -pin_load 0.0060 [get_ports {output_o[80]}]
set_load -pin_load 0.0060 [get_ports {output_o[79]}]
set_load -pin_load 0.0060 [get_ports {output_o[78]}]
set_load -pin_load 0.0060 [get_ports {output_o[77]}]
set_load -pin_load 0.0060 [get_ports {output_o[76]}]
set_load -pin_load 0.0060 [get_ports {output_o[75]}]
set_load -pin_load 0.0060 [get_ports {output_o[74]}]
set_load -pin_load 0.0060 [get_ports {output_o[73]}]
set_load -pin_load 0.0060 [get_ports {output_o[72]}]
set_load -pin_load 0.0060 [get_ports {output_o[71]}]
set_load -pin_load 0.0060 [get_ports {output_o[70]}]
set_load -pin_load 0.0060 [get_ports {output_o[69]}]
set_load -pin_load 0.0060 [get_ports {output_o[68]}]
set_load -pin_load 0.0060 [get_ports {output_o[67]}]
set_load -pin_load 0.0060 [get_ports {output_o[66]}]
set_load -pin_load 0.0060 [get_ports {output_o[65]}]
set_load -pin_load 0.0060 [get_ports {output_o[64]}]
set_load -pin_load 0.0060 [get_ports {output_o[63]}]
set_load -pin_load 0.0060 [get_ports {output_o[62]}]
set_load -pin_load 0.0060 [get_ports {output_o[61]}]
set_load -pin_load 0.0060 [get_ports {output_o[60]}]
set_load -pin_load 0.0060 [get_ports {output_o[59]}]
set_load -pin_load 0.0060 [get_ports {output_o[58]}]
set_load -pin_load 0.0060 [get_ports {output_o[57]}]
set_load -pin_load 0.0060 [get_ports {output_o[56]}]
set_load -pin_load 0.0060 [get_ports {output_o[55]}]
set_load -pin_load 0.0060 [get_ports {output_o[54]}]
set_load -pin_load 0.0060 [get_ports {output_o[53]}]
set_load -pin_load 0.0060 [get_ports {output_o[52]}]
set_load -pin_load 0.0060 [get_ports {output_o[51]}]
set_load -pin_load 0.0060 [get_ports {output_o[50]}]
set_load -pin_load 0.0060 [get_ports {output_o[49]}]
set_load -pin_load 0.0060 [get_ports {output_o[48]}]
set_load -pin_load 0.0060 [get_ports {output_o[47]}]
set_load -pin_load 0.0060 [get_ports {output_o[46]}]
set_load -pin_load 0.0060 [get_ports {output_o[45]}]
set_load -pin_load 0.0060 [get_ports {output_o[44]}]
set_load -pin_load 0.0060 [get_ports {output_o[43]}]
set_load -pin_load 0.0060 [get_ports {output_o[42]}]
set_load -pin_load 0.0060 [get_ports {output_o[41]}]
set_load -pin_load 0.0060 [get_ports {output_o[40]}]
set_load -pin_load 0.0060 [get_ports {output_o[39]}]
set_load -pin_load 0.0060 [get_ports {output_o[38]}]
set_load -pin_load 0.0060 [get_ports {output_o[37]}]
set_load -pin_load 0.0060 [get_ports {output_o[36]}]
set_load -pin_load 0.0060 [get_ports {output_o[35]}]
set_load -pin_load 0.0060 [get_ports {output_o[34]}]
set_load -pin_load 0.0060 [get_ports {output_o[33]}]
set_load -pin_load 0.0060 [get_ports {output_o[32]}]
set_load -pin_load 0.0060 [get_ports {output_o[31]}]
set_load -pin_load 0.0060 [get_ports {output_o[30]}]
set_load -pin_load 0.0060 [get_ports {output_o[29]}]
set_load -pin_load 0.0060 [get_ports {output_o[28]}]
set_load -pin_load 0.0060 [get_ports {output_o[27]}]
set_load -pin_load 0.0060 [get_ports {output_o[26]}]
set_load -pin_load 0.0060 [get_ports {output_o[25]}]
set_load -pin_load 0.0060 [get_ports {output_o[24]}]
set_load -pin_load 0.0060 [get_ports {output_o[23]}]
set_load -pin_load 0.0060 [get_ports {output_o[22]}]
set_load -pin_load 0.0060 [get_ports {output_o[21]}]
set_load -pin_load 0.0060 [get_ports {output_o[20]}]
set_load -pin_load 0.0060 [get_ports {output_o[19]}]
set_load -pin_load 0.0060 [get_ports {output_o[18]}]
set_load -pin_load 0.0060 [get_ports {output_o[17]}]
set_load -pin_load 0.0060 [get_ports {output_o[16]}]
set_load -pin_load 0.0060 [get_ports {output_o[15]}]
set_load -pin_load 0.0060 [get_ports {output_o[14]}]
set_load -pin_load 0.0060 [get_ports {output_o[13]}]
set_load -pin_load 0.0060 [get_ports {output_o[12]}]
set_load -pin_load 0.0060 [get_ports {output_o[11]}]
set_load -pin_load 0.0060 [get_ports {output_o[10]}]
set_load -pin_load 0.0060 [get_ports {output_o[9]}]
set_load -pin_load 0.0060 [get_ports {output_o[8]}]
set_load -pin_load 0.0060 [get_ports {output_o[7]}]
set_load -pin_load 0.0060 [get_ports {output_o[6]}]
set_load -pin_load 0.0060 [get_ports {output_o[5]}]
set_load -pin_load 0.0060 [get_ports {output_o[4]}]
set_load -pin_load 0.0060 [get_ports {output_o[3]}]
set_load -pin_load 0.0060 [get_ports {output_o[2]}]
set_load -pin_load 0.0060 [get_ports {output_o[1]}]
set_load -pin_load 0.0060 [get_ports {output_o[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ena_i}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_ni[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_ni[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_ni[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_ni[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_ni[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_ni[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_ni[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
