// Auto-generated by LibreLane
module hdecoder(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input ena_i,
  input[6:0] input_ni,
  output[127:0] output_o,
  output[127:0] output_no
);
endmodule
